version: "3"
services:
  web:
    build: .
    container_name: web
    restart: on-failure
    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: hapi-fhir-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
